# This is a basic workflow to help you get started with Actions

name: Unit tests

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  pytest:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          if [ -f requirements_test.txt ]; then pip install -r requirements_test.txt; fi
          pip install -e $GITHUB_WORKSPACE
      - name: Pytest run
        run: |
          coverage run --omit="*tests*" -m pytest -svv -m "not docker_required"
      - name: Coverage report
        run: |
          coverage report

  pytest-e2e-with-cluster:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          sif [ -f requirements_test.txt ]; then pip install -r requirements_test.txt; fi
          pip install -e $GITHUB_WORKSPACE
      - name: Pytest run
        run: |
          coverage run --omit="*tests*" -m pytest -svv -m "docker_required"
      - name: Coverage report
        run: |
          coverage report